export enum BusinessType {
  AUTOSERVICIO = 'AUTOSERVICIO',
  TIENDA_DE_ROPA = 'TIENDA_DE_ROPA',
  GYM = 'GYM',
  HOTEL = 'HOTEL',
  HOSTAL = 'HOSTAL',
  MOTEL = 'MOTEL',
  PANADERIA = 'PANADERIA',
  FERRETERIA = 'FERRETERIA',
}